services:
  ml-visualizations:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
